name: Lint Code Base

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main", "feat/*" ]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Set owner of working dir recurively (Linux)
        run: sudo chown -R $(whoami) .

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVA: true
          JAVA_FILE_NAME: checkstyle.xml
          DEFAULT_BRANCH: main
          LINTER_RULES_PATH: /
          FILTER_REGEX_EXCLUDE: .*src/test.*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}