name: Java CI for Test

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main", "feat/*" ]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        ports:
          - 17252:3306
        env:
          MYSQL_ROOT_PASSWORD: test
          MYSQL_DATABASE: PUPPY_PLACE_USER_TEST

    steps:
      - name: Set owner of working dir recurively (Linux)
        run: sudo chown -R $(whoami) .

      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make directories
        run: mkdir -p build/generated-snippets

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Test with Gradle
        run: ./gradlew test